@startuml Arquitectura Distribuida GCP - Centro de Salud

title Arquitectura Distribuida de Alta Disponibilidad (GCP)
caption Universidad OSDS - Sistemas Operativos y Distribuidos

skinparam shadowing false
skinparam packageStyle rectangle
skinparam componentStyle rectangle
skinparam defaultTextAlignment center

' Paleta de colores
skinparam node {
    BorderColor #2c3e50
    BackgroundColor #f8f9fa
}
skinparam database {
    BorderColor #d35400
    BackgroundColor #fdf2e9
}

cloud "INTERNET (Tráfico Público)" as PUBLIC_NET {
    node "Navegador Cliente\n(Personal de Salud)" as CLIENT
}

package "Google Cloud Platform - VPC Network" as GCP_VPC {

    ' VM 3: Gateway de Entrada y Seguridad
    node "VM 3: Gateway & Seguridad\n(IP Pública: 34.XX.XX.XX / IP Interna: 10.128.0.30)" as VM3 #e8f8f5 {
        component "Nginx Reverse Proxy\n(Puerto 80/443)" as NGINX
        folder "Frontend Estático\n(index.html)" as HTML_STATIC
        
        NGINX -right-> HTML_STATIC : Sirve archivos
    }

    ' VM 1: Hospital Local (Edge Server Emulado)
    node "VM 1: Hospital Local\n(IP Interna: 10.128.0.10)" as VM1 #ebf5fb {
        component "app-estaciones\n(Node.js / Express)" as APP_LOCAL
        database "db-local\n(PostgreSQL 16)" as DB_LOCAL
        
        APP_LOCAL -down-> DB_LOCAL : Conexión Local (Puerto 5432)
    }

    ' VM 2: Centro de Datos Nube (Core Cloud Server)
    node "VM 2: Nube Central\n(IP Interna: 10.128.0.20)" as VM2 #fef9e7 {
        component "app-terminales\n(Node.js / Express)" as APP_CLOUD
        database "db-nube\n(PostgreSQL 16)" as DB_CLOUD
        
        APP_CLOUD -down-> DB_CLOUD : Conexión Local (Puerto 5432)
    }

}

' ---- FLUJOS DE COMUNICACIÓN ----

' 1. Carga del Frontend
CLIENT ==> NGINX : 1. Petición HTTP/HTTPS (Puerto 80/443)
NGINX ==> CLIENT : Retorna Frontend Estático (index.html)

' 2. Conexiones WebSocket en Tiempo Real
CLIENT --> NGINX : 2. Solicitud de WebSockets (WS/WSS)

NGINX ---> APP_LOCAL : Redirección /ws-medicas\n(IP Interna VM 1 - Puerto 8001) #blue
NGINX ---> APP_CLOUD : Redirección /ws-administrativas\n(IP Interna VM 2 - Puerto 8002) #darkcyan

' 3. Replicación Lógica Bidireccional
DB_LOCAL <=====> DB_CLOUD : 3. Replicación Lógica PostgreSQL\n(IPs Privadas VPC - Puerto 5432)\nFiltros por origen_registro & origin = none #red

@enduml
