@startuml "Arquitectura Centro Médico"
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam componentStyle rectangle
skinparam defaultTextAlignment center

'======================
' BASES DE DATOS
'======================

package "Base de Datos 1" {

database "Instancia de\nMariaDB" as MariaDB
database "Réplica" as MariaReplica

component "Orquestador" as OrchMaria

MariaReplica -left- MariaDB
OrchMaria ..down.. MariaDB
}

package "Base de Datos 2" {

database "Instancia de\nPostgreSQL" as PostgreSQL
database "Réplica" as PostgresReplica

component "Orquestador" as OrchPostgres

PostgresReplica -left- PostgreSQL
OrchPostgres ..up.. PostgreSQL
}

package "Base de Datos 3" {

database "Instancia de\nMySQL u Otro" as MySQL
database "Réplica" as MyReplica

component "Orquestador" as OrchMy

MyReplica -right- MySQL
OrchMy ..up.. MySQL
}

'======================
' APLICACIONES
'======================

node "Aplicación 1" as App1
node "Réplica de App" as App1Replica

node "Aplicación 2" as App2
node "Réplica de App" as App2Replica

node "Aplicación 3" as App3

App1Replica -down- App1
App2Replica -down- App2

'======================
' MIDDLEWARE
'======================

rectangle "Middleware" as MW

'======================
' USUARIOS
'======================

actor "Usuarios" as U1
actor "Usuarios" as U2
actor "Usuarios" as U3

'======================
' CONEXIONES
'======================

App1 --> MariaDB
App2 --> PostgreSQL
App3 --> MySQL

U1 --> App1
App1 --> U1

U2 --> App2
App2 --> U2

U3 --> App3
App3 --> U3

App1 --> MW
App2 --> MW

MW <--> App3

App3 --> MySQL

@enduml