version: '3.8'

services:
  nginx-proxy:
    # NPM conectado con cloudflared
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/frontend:/usr/share/nginx/html:ro
    networks:
      - hospital_net
      - cloud_net
      - dmz_net # Red que conecta el tunel con el NPM

  tunnel:
    # Todo el trafico entra por Cloudflare que ya tiene medidas de seguridad y luego lo redirige al nginx-proxy:80
    image: cloudflare/cloudflared:latest # Para no abrir puertos Ingress y reducir la superficie de ataque
    container_name: cloudflare-tunnel # abriendo un canal de salida cifrado hacia la red global de Cloudflare
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - dmz_net

networks:
  hospital_net:
    driver: bridge
    name: hospital_net
  cloud_net:
    driver: bridge
    name: cloud_net
  dmz_net:
    driver: bridge
    name: dmz_net
